@startuml
/' left to right direction '/
node Client
package "Hub 1" as H1 {
  node "Node 1" as N1 {
    component [REST Server]
    node Vault {
      interface "Vault Access" as VA
      database "Vault database" as VD
    }
  }
  node "Node 2" as N2 {
    [Config File]
  }
  node "Node 3" as N3
}

/' package "Hub 2" as H2 { '/
/'   node "Node 2" '/ 
/'   node "Node 4" '/
/'   node "Node 5" '/
/' } '/

Client -right-> [REST Server] 
[REST Server] -right-> VA 
VA -right-> VD
@enduml
