@startuml
actor Alice
actor Bob
box "Node A Server" 
  participant "Node" as NA
  database "Vault Index" as VI
    entity "Bob's Vault" as BV
    database "Bob's Vault DB" as VD
end box
participant "Node B" as NB
group Add Trustee
  Bob -> NA++: Add Trustee
  NA -> BV: Put data
  note right : Alice's public key
end
Alice -> NA: Issue credential to Bob 
NA -> VI: Retrive vault host node

alt exist in current node
  NA -> NA: Authorization
  group Bob's Vault
    NA -> BV: Put data
    BV -> BV: Verify
    BV -> VD: Save data
    BV <-- VD: Return response
  end
  NA <-- BV: Return response
  Alice <-- NA: Return response
else broadcast to neighbor nodes
  NA --> NB: Broadcast Message
end

@enduml
