@startuml
node Node {
  [REST Server]
  [Backend Server]
  database "Vault Index"
  component Config
  interface VaultInterface
  node Vault {
    component VerificationMethod
    database  "Vault database"
  }
}
/' [REST Server] -> [Backend Server] '/
/' [Backend Server] -> VerificationMethod '/
/' Vault -right-|> VaultInterface '/
@enduml
