@startuml
actor Alice
box "Node A Server" 
  participant "Node" as NA
  database "Vault Index" as VI
    entity "Alice's Vault" as AV
    database "Alice's Vault DB" as VD
end box
participant "Node B" as NB

Alice -> NA: Save data request
NA -> VI: Retrive vault host node
alt exist in current node
  NA -> NA: Authorize
  group Alice's Vault
    NA -> AV: Put data
    AV -> AV: Verify
    AV -> VD: Save data
    AV <-- VD: Return response
  end
  NA <-- AV: Return response
  Alice <-- NA: Return response
else broadcast to neighbor nodes
  NA --> NB: Broadcast Message
end

@enduml
