@startuml
actor  Alice 
actor  Bob 
boundary Node
entity "Alice's Vault" as AV 

Alice -> Alice: Create Access Credential for Bob
Alice -> Bob: Send Credential
Bob -> Node: Access Request
Node -> Node: Authorizaion
Node -> AV: Get Data
Node -> Bob: Response
@enduml
